### PR TITLE
Xcode12.4

### PR DESCRIPTION
**Pull request by isghe**
Compile OK on Xcode Version 12.4 (12D4e), macOS Catalina Version 10.15.7:

* add missing bcndecode.cpp/h and skidmarks.cpp/h to vdrift.xcodeproj
* Avoid compilation error: Argument value 10880 is outside the valid range [0, 255] btVector3.h

### CODE REVIEW

**Comment by logzero** [comment]
It looks like the issue with bullet has been fixed upstream.
https://github.com/bulletphysics/bullet3/blob/master/src/LinearMath/btVector3.h#L39

Is there a way to just use upstream bullet instead of maintaining a copy?
